#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Restore a project from a Markdown file generated by export_code_to_md.py.
Supports Windows, macOS, and Linux.
"""

import re
import sys
from pathlib import Path

def restore_project_from_md(md_file: str = "project_code.md", output_dir: str = "restored_project"):
    md_path = Path(md_file).resolve()
    if not md_path.is_file():
        print(f"❌ Error: Input file '{md_file}' not found.", file=sys.stderr)
        return False

    output_root = Path(output_dir).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    # 读取 Markdown 内容
    try:
        with open(md_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"❌ Failed to read {md_file}: {e}", file=sys.stderr)
        return False

    # 正则匹配：标题中的路径 + 代码块内容
    # 匹配示例：
    # ## `src/main.py`
    #
    # ```py
    # print("hello")
    # ```
    pattern = r'^#{2,6}\s*`([^`\n]+)`\s*\n\n\s*```(?:\w*)?\n(.*?)\n```'
    matches = re.findall(pattern, content, re.DOTALL | re.MULTILINE)

    if not matches:
        print("⚠️ No valid code blocks with file paths found.", file=sys.stderr)
        # 调试：打印前几个包含反引号的标题行
        lines = content.splitlines()
        candidates = [line.strip() for line in lines if line.strip().startswith('#') and '`' in line]
        if candidates:
            print("🔍 Found possible path lines (but may not match format):")
            for c in candidates[:5]:
                print(f"  - {c}")
        return False

    print(f"📦 Found {len(matches)} files to restore. Output directory: {output_root}")
    restored = 0

    for rel_path_str, code in matches:
        rel_path_str = rel_path_str.strip()

        # 跳过空路径
        if not rel_path_str:
            continue

        # 使用 pathlib 处理路径（自动跨平台）
        try:
            rel_path = Path(rel_path_str)
            # 拒绝绝对路径或包含 .. 的路径（安全防护）
            if rel_path.is_absolute() or '..' in rel_path.parts:
                print(f"⚠️ Skipped unsafe path: {rel_path_str}")
                continue

            target_file = output_root / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)

            # 写入文件（保留原始换行，但去除末尾多余空行）
            clean_code = code.rstrip('\n')
            with open(target_file, 'w', encoding='utf-8', newline='') as f:
                f.write(clean_code)

            print(f"✅ {rel_path}")
            restored += 1

        except (OSError, ValueError) as e:
            print(f"❌ Failed to write '{rel_path_str}': {e}", file=sys.stderr)

    print(f"\n🎉 Successfully restored {restored} files to: {output_root}")
    return True

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Restore project files from a Markdown export (e.g., project_code.md)."
    )
    parser.add_argument(
        "-i", "--input",
        default="project_code.md",
        help="Input Markdown file (default: project_code.md)"
    )
    parser.add_argument(
        "-o", "--output",
        default="restored_project",
        help="Output directory to restore files (default: restored_project)"
    )
    args = parser.parse_args()

    success = restore_project_from_md(args.input, args.output)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
